//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestPracticeChecker.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BestPracticeChecker.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CategoryCorrectness {
            get {
                return ResourceManager.GetString("CategoryCorrectness", resourceCulture);
            }
        }
        
        internal static string CategoryPerformance {
            get {
                return ResourceManager.GetString("CategoryPerformance", resourceCulture);
            }
        }
        
        internal static string CategoryTypeSafety {
            get {
                return ResourceManager.GetString("CategoryTypeSafety", resourceCulture);
            }
        }
        
        internal static string CategoryCodeStyle {
            get {
                return ResourceManager.GetString("CategoryCodeStyle", resourceCulture);
            }
        }
        
        internal static string ConditionalDebugTitle {
            get {
                return ResourceManager.GetString("ConditionalDebugTitle", resourceCulture);
            }
        }
        
        internal static string ConditionalDebugMessageFormat {
            get {
                return ResourceManager.GetString("ConditionalDebugMessageFormat", resourceCulture);
            }
        }
        
        internal static string InefficientStringApiMessageFormat {
            get {
                return ResourceManager.GetString("InefficientStringApiMessageFormat", resourceCulture);
            }
        }
        
        internal static string InefficientStringApiTitle {
            get {
                return ResourceManager.GetString("InefficientStringApiTitle", resourceCulture);
            }
        }
        
        internal static string IllegalMethodInUpdateMessageFormat {
            get {
                return ResourceManager.GetString("IllegalMethodInUpdateMessageFormat", resourceCulture);
            }
        }
        
        internal static string IllegalMethodInUpdateTitle {
            get {
                return ResourceManager.GetString("IllegalMethodInUpdateTitle", resourceCulture);
            }
        }
        
        internal static string ConstTagsMessageFormat {
            get {
                return ResourceManager.GetString("ConstTagsMessageFormat", resourceCulture);
            }
        }
        
        internal static string ConstTagsTitle {
            get {
                return ResourceManager.GetString("ConstTagsTitle", resourceCulture);
            }
        }
        
        internal static string CameraMainInUpdateMessageFormat {
            get {
                return ResourceManager.GetString("CameraMainInUpdateMessageFormat", resourceCulture);
            }
        }
        
        internal static string CameraMainInUpdateTitle {
            get {
                return ResourceManager.GetString("CameraMainInUpdateTitle", resourceCulture);
            }
        }
        
        internal static string NonAllocatingPhysicEngineMessageFormat {
            get {
                return ResourceManager.GetString("NonAllocatingPhysicEngineMessageFormat", resourceCulture);
            }
        }
        
        internal static string NonAllocatingPhysicEngineTitle {
            get {
                return ResourceManager.GetString("NonAllocatingPhysicEngineTitle", resourceCulture);
            }
        }
        
        internal static string CompareStringWithOrdinalMessageFormat {
            get {
                return ResourceManager.GetString("CompareStringWithOrdinalMessageFormat", resourceCulture);
            }
        }
        
        internal static string CompareStringWithOrdinalTitle {
            get {
                return ResourceManager.GetString("CompareStringWithOrdinalTitle", resourceCulture);
            }
        }
        
        internal static string ObjectFindAndTypeMessageFormat {
            get {
                return ResourceManager.GetString("ObjectFindAndTypeMessageFormat", resourceCulture);
            }
        }
        
        internal static string ObjectFindAndTypeTitle {
            get {
                return ResourceManager.GetString("ObjectFindAndTypeTitle", resourceCulture);
            }
        }
        
        internal static string SmallClassesMessageFormat {
            get {
                return ResourceManager.GetString("SmallClassesMessageFormat", resourceCulture);
            }
        }
        
        internal static string SmallClassesTitle {
            get {
                return ResourceManager.GetString("SmallClassesTitle", resourceCulture);
            }
        }
        
        internal static string StringReferencesMessageFormat {
            get {
                return ResourceManager.GetString("StringReferencesMessageFormat", resourceCulture);
            }
        }
        
        internal static string StringReferencesTitle {
            get {
                return ResourceManager.GetString("StringReferencesTitle", resourceCulture);
            }
        }
    }
}
